### PR TITLE
Handle loops in codemod

### PR DESCRIPTION
**Pull request by blimmer**
I noticed that this didn't convert quite right on my codebase. Everything else worked great!

### CODE REVIEW

**Comment by lorcan** [comment]
Great to hear it mostly worked :-)
Thanks for providing a failing test case! I'll merge this in if/when somebody/I put together a fix :-)

**Comment by blimmer** [comment]
@lorcan it was pretty easy to fix - this PR is updated with the fix!

**Comment by blimmer** [comment]
also you might consider flipping on travis-ci - i added a simple config in this PR to run the test inline:

https://travis-ci.org/blimmer/test-selectors-codemod/builds/282029157

**Comment by lorcan** [comment]
This is brilliant! Thanks so much @blimmer!

**Comment by lorcan** [comment]
Set up travis-ci too. Thanks for providing the config :+1:

**Comment by blimmer** [comment]
no problem - glad to help.

**Pull request merged**
